server:
  port: 8090
spring:
  application:
    name: "loans"
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"


