build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "Sandeep Mishra - Developer"
    email: "sandeepmishra898k@gmail.com"
  onCallSupport:
    - 8984348365