spring:
  config:
    activate:
      on-profile: "prod"


build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Sandeep Mishra - Developer"
    email: "sandeepmishra898k@gmail.com"
  onCallSupport:
    - 8984348365